services:
  - type: web
    name: gate-qr-system
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: gateqr-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: QR_SCANNER_SYSTEM
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false

databases:
  - name: gateqr-db
    plan: free
    region: singapore
    databaseName: QR_SCANNER_SYSTEM
    user: root
